### ISSUE TITLE
I get the following error when trying to execute 

### ISSUE THREAD

**Issue by fortolano** [jungwhank/fake-review-generator#1]
Hi Jung,
I have a VM server on DigitalOcean running Ubuntu 64bit, with Anaconda 64bit. The VM has 16 GB RAM + 10GB swap memory.  But when I execute preprocess.py, I get the following errors (image attached). 

Can you please help give me some guidance?  I'm stuck!

thanks in advance!

Cheers
Flavio

<img width="830" alt="Screen Shot 2020-06-05 at 7 33 09 PM" src="https://user-images.githubusercontent.com/9613824/83934166-7aad4c80-a763-11ea-805e-19dfc7c5987a.png">

**Comment by jungwhank** [comment]
Hello, @fortolano 

Can you try this code?
change this line below in `preprocess.py`
```python
df = pd.read_json(review_path, lines=True)
```
to
```python
df_lines = [json.loads(line) for line in open(review_path, 'r')]
df = pd.DataFrame(df_lines)
```
